### ISSUE TITLE
How are you annotating the images?

### ISSUE THREAD

**Issue by mfethe1** [MahmudulAlam/Complete-Blood-Cell-Count-Dataset#1]
Could you provide a useful way to annotate images. I'd like to use your program but need to figure out the annotation method first. If you could provide that information it would be very useful.

**Comment by MahmudulAlam** [comment]
Hi @mfethe1 
I didn't annotate those images. However, you can annotate the same you using [LabelImg][1]. It produces the annotations in the XML format. 

[1]: https://github.com/tzutalin/labelImg
